apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo-app
  name: wiki
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki
            image: teemukoivumaa/wiki:1.1
          restartPolicy: Never
