apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-log
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
<<<<<<< Updated upstream
          image: teemukoivumaa/todo-app:0.6
=======
          image: teemukoivumaa/todo-app:0.7
>>>>>>> Stashed changes
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-log
            mountPath: /usr/src/app/files
