apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-app
  name: todo-app-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
