apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: random-strings
  name: random-strings-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
