apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
              subPath: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
          envFrom:
            - secretRef:
                name: dbpass
  volumeClaimTemplates: #VolumeClaim
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
