apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: random-strings
  name: postgres-ss
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /data 
          env:
            - name: POSTGRES_USER
              value: "postgres"
          envFrom:
            - secretRef:
                name: dbpass
  volumeClaimTemplates: #VolumeClaim
    - metadata:
        namespace: random-strings
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
