name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: project-cluster
  GKE_ZONE: europe-north1-b
  FRONTEND_IMAGE: todo-frontend
  BACKEND_IMAGE: todo-backend
  WIKI_IMAGE: todo-wiki
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@main'
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true
      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" ./todo-app/frontend
          docker build --tag "gcr.io/$PROJECT_ID/$BACKEND_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" ./todo-app/backend
          docker build --tag "gcr.io/$PROJECT_ID/$WIKI_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" ./todo-app/wiki
          
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Deploy
        run: |-
          kustomize edit set image gcr.io/PROJECT_ID/IMAGE=gcr.io/$PROJECT_ID/$FRONT_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build ./3/3.3/front | kubectl apply -f -
          kubectl rollout status deployment $FRONTEND_IMAGE
          kubectl get services -o wide
          
          kustomize edit set image gcr.io/PROJECT_ID/IMAGE=gcr.io/$PROJECT_ID/$BACK_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build ./3/3.3/back | kubectl apply -f -
          kubectl rollout status deployment $BACKEND_IMAGE
          kubectl get services -o wide
          
          kustomize edit set image gcr.io/PROJECT_ID/IMAGE=gcr.io/$PROJECT_ID/$WIKI_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build ./3/3.3/wiki | kubectl apply -f -
          kubectl rollout status deployment $WIKI_IMAGE
          kubectl get services -o wide
